export type Market = {
  name: string;
  slug: string;
  flag: string;
  port: string;
  note: string;
  // Extended data for country pages
  region: string;
  popularVehicles: string[];
  marketSize: string;
  keyProducts: string[];
  metaTitle: string;
  metaDescription: string;
  h1: string;
  intro: string;
  whyPopular: string;
  ourSupply: string;
  shippingNote: string;
  faqItems: { q: string; a: string }[];
};

export const markets: Market[] = [
  {
    name: "Nigeria",
    slug: "nigeria",
    flag: "🇳🇬",
    port: "Lagos (Apapa)",
    region: "West Africa",
    note: "Africa's largest 2-wheeler market. 1M+ motorcycles sold annually. Keke Napep is primary urban transport.",
    popularVehicles: ["Bajaj RE (Keke Napep)", "Bajaj Boxer", "TVS HLX", "CT100"],
    marketSize: "1M+ motorcycles sold annually — Africa's largest 2-wheeler market",
    keyProducts: ["Keke Napep engine parts", "Bajaj Boxer frame components", "3-wheeler gearbox parts", "brake assemblies"],
    metaTitle: "Spare Parts Supplier for Nigeria — Bajaj, TVS, Keke Napep Parts | CrestMAX",
    metaDescription: "CrestMAX supplies wholesale Bajaj, TVS and Keke Napep spare parts to Nigeria importers. FOB Mumbai or CIF Lagos (Apapa). B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for Nigeria — Bajaj, TVS & Keke Napep",
    intro: "Nigeria is Africa's largest 2-wheeler and 3-wheeler market, with over one million motorcycles sold annually and the Keke Napep (Bajaj RE auto-rickshaw) serving as the backbone of urban transport in Lagos, Kano, Port Harcourt and dozens of cities. CrestMAX exports wholesale spare parts from Ludhiana, India directly to Nigerian importers, distributors and trading companies — shipped FOB Mumbai or CIF Lagos Apapa port.",
    whyPopular: "The Bajaj RE tricycle — locally called Keke Napep — dominates last-mile transport across Nigeria, creating constant demand for engine parts, gearboxes, brake assemblies and body panels. Bajaj Boxer and CT100 motorcycles are equally popular for commercial dispatch and rural transport. Nigerian importers buy in bulk and need a reliable Indian supplier with consistent stock, OEM-quality parts, and proper export documentation.",
    ourSupply: "CrestMAX stocks parts for all major 2-wheeler and 3-wheeler models popular in Nigeria: Bajaj RE (Keke Napep) engine components, crankshafts, gearbox parts and body panels; Bajaj Boxer engine, suspension and brake parts; CT100 engine kits; TVS HLX motorcycle parts. All parts are sourced from specialist aftermarket manufacturers in Ludhiana — India's spare parts manufacturing capital.",
    shippingNote: "We ship from Mumbai port to Lagos Apapa container port. Typical transit time is 18–22 days. We provide full export documentation including commercial invoice, packing list, certificate of origin, and bill of lading. Terms available: FOB Mumbai or CIF Lagos.",
    faqItems: [
      { q: "What is the minimum order for Nigeria?", a: "We work on wholesale quantities — typically one 20-foot container or LCL consolidation depending on your order volume. Contact us for MOQ details specific to your product mix." },
      { q: "Do you supply Keke Napep (Bajaj RE) spare parts?", a: "Yes — Bajaj RE parts are one of our strongest categories. We supply engine parts, gearboxes, brake assemblies, body panels and electrical components for Keke Napep." },
      { q: "Can you ship CIF to Lagos Apapa?", a: "Yes. We offer both FOB Mumbai and CIF Lagos (Apapa Port) terms. We work with freight forwarders experienced on the India–Nigeria corridor." },
      { q: "What documents do you provide?", a: "Full export documentation: commercial invoice, packing list, certificate of origin, HS codes, and bill of lading. NAFDAC or SONCAP pre-shipment inspection can be arranged on request." },
    ],
  },
  {
    name: "Ghana",
    slug: "ghana",
    flag: "🇬🇭",
    port: "Tema Port",
    region: "West Africa",
    note: "Fast-growing aftermarket. Strong demand for Boxer and CT100 parts.",
    popularVehicles: ["Bajaj Boxer", "CT100", "TVS HLX"],
    marketSize: "One of West Africa's fastest-growing motorcycle aftermarkets",
    keyProducts: ["Bajaj Boxer engine parts", "CT100 spares", "TVS HLX components", "suspension and brake parts"],
    metaTitle: "Spare Parts Supplier for Ghana — Bajaj Boxer, CT100 Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj Boxer, CT100 and TVS spare parts to Ghana importers. CIF Tema Port or FOB Mumbai. B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for Ghana — Bajaj Boxer & CT100",
    intro: "Ghana's motorcycle aftermarket is one of West Africa's fastest-growing, with strong demand for Bajaj Boxer, CT100 and TVS HLX parts from importers in Accra, Kumasi and Tema. CrestMAX exports wholesale 2-wheeler spare parts from Ludhiana, India to Ghanaian importers and distributors — shipped FOB Mumbai or CIF Tema Port.",
    whyPopular: "The Bajaj Boxer is Ghana's most widely used commercial motorcycle, relied upon for courier services, rural transport and agri-logistics across the country. CT100 is popular in peri-urban areas. As these fleets grow, the demand for affordable, quality spare parts imported directly from India continues to rise. Ghanaian importers are increasingly bypassing middlemen and sourcing directly from Indian exporters like CrestMAX.",
    ourSupply: "We supply a full range of parts for Bajaj Boxer (engine kits, crankshafts, pistons, clutch plates, brake pads, sprockets, chain sets), CT100 (engine components, carburettors, electrical), and TVS HLX (engine parts, suspension, filters). All products are OEM-quality, sourced from Ludhiana manufacturers with over a decade of export experience.",
    shippingNote: "We ship from Mumbai to Tema Container Port, Ghana's main import gateway. Typical transit time is 20–25 days. We provide all export documentation required for Ghanaian customs clearance, including ECOWAS certificate of origin where required.",
    faqItems: [
      { q: "Do you supply Bajaj Boxer parts for Ghana?", a: "Yes — Bajaj Boxer parts are a core product line. We stock engine kits, pistons, crankshafts, clutch plates, brake parts, suspension components and electrical parts for the Boxer." },
      { q: "What is the shipping time from India to Ghana?", a: "From Mumbai to Tema Port, typical ocean transit is 20–25 days. Add 3–5 days for port clearance and inland delivery." },
      { q: "Can you provide ECOWAS certificate of origin?", a: "Yes. We provide ECOWAS Form A certificate of origin for all shipments to ECOWAS member countries including Ghana." },
      { q: "Do you offer CIF Tema pricing?", a: "Yes. We can quote on both FOB Mumbai and CIF Tema Port basis. Contact us with your product list for a tailored quotation." },
    ],
  },
  {
    name: "Kenya",
    slug: "kenya",
    flag: "🇰🇪",
    port: "Mombasa",
    region: "East Africa",
    note: "Major East African hub. High Bajaj RE penetration in urban areas.",
    popularVehicles: ["Bajaj RE", "Bajaj Boxer", "TVS HLX", "TVS King"],
    marketSize: "East Africa's largest import hub — gateway to Uganda, Rwanda, DRC",
    keyProducts: ["Bajaj RE auto-rickshaw parts", "Boda Boda parts", "TVS King 3-wheeler components", "engine overhaul kits"],
    metaTitle: "Spare Parts Supplier for Kenya — Bajaj RE, Boda Boda & TVS Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj RE, TVS and Boda Boda spare parts to Kenya importers. CIF Mombasa or FOB Mumbai. East Africa's trusted Indian supplier.",
    h1: "Wholesale Spare Parts Supplier for Kenya — Bajaj RE, TVS & Boda Boda Parts",
    intro: "Kenya is East Africa's largest import hub and the primary gateway for spare parts reaching Uganda, Rwanda, Tanzania and DR Congo. The Boda Boda motorcycle taxi industry and Bajaj RE auto-rickshaw fleet drive massive ongoing demand for Indian spare parts. CrestMAX exports wholesale 2-wheeler and 3-wheeler parts from Ludhiana to Kenyan importers and distributors — shipped CIF Mombasa or FOB Mumbai.",
    whyPopular: "The Boda Boda (motorcycle taxi) is the most important mode of transport in Kenya's cities and rural areas — Nairobi, Mombasa, Kisumu and hundreds of towns all depend on it. With hundreds of thousands of motorcycles in operation, the demand for engine parts, brake systems, electrical components and overhaul kits is constant. Bajaj RE 3-wheelers serve as Nairobi's informal transit layer, creating parallel demand for tricycle parts.",
    ourSupply: "CrestMAX supplies Bajaj RE (engine parts, gearboxes, body panels), Bajaj Boxer (engine kits, suspension, brakes), TVS HLX (motorcycle parts, filters, electrical), and TVS King (3-wheeler engine and body parts) to Kenyan buyers. Our Ludhiana sourcing network ensures consistent stock availability and competitive pricing for large wholesale orders.",
    shippingNote: "We ship from Mumbai to Mombasa Port — East Africa's largest container terminal. Typical transit time is 18–22 days. Kenya is also a hub for regional distribution, and we can structure shipments for onward delivery to Uganda, Rwanda or Tanzania.",
    faqItems: [
      { q: "Do you supply Boda Boda spare parts?", a: "Yes — Boda Boda motorcycles are mostly Bajaj Boxer and TVS HLX models. We supply a full range of parts for both: engine kits, pistons, brake systems, suspension, electrical components and filters." },
      { q: "Can Kenyan importers buy for onward distribution to Uganda or Rwanda?", a: "Yes — Mombasa is a regional hub. Many of our Kenyan buyers distribute parts across East Africa. We can structure documentation accordingly." },
      { q: "What is the transit time from India to Mombasa?", a: "Typically 18–22 days ocean transit from Mumbai. Add port clearance time (3–7 days) for delivery to Nairobi or upcountry." },
      { q: "Do you have experience with Kenya Revenue Authority import requirements?", a: "Yes — we provide all standard export documentation compatible with KRA import procedures including commercial invoice, packing list, certificate of origin and bill of lading." },
    ],
  },
  {
    name: "Tanzania",
    slug: "tanzania",
    flag: "🇹🇿",
    port: "Dar es Salaam",
    region: "East Africa",
    note: "Rising demand for motorcycle taxi (Boda Boda) spare parts.",
    popularVehicles: ["Bajaj Boxer", "TVS HLX", "Bajaj RE"],
    marketSize: "Fast-growing Boda Boda economy with rising import demand",
    keyProducts: ["Bajaj Boxer parts", "Boda Boda spares", "engine kits", "suspension components"],
    metaTitle: "Spare Parts Supplier for Tanzania — Bajaj Boxer & Boda Boda Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj Boxer, TVS and Boda Boda spare parts to Tanzania importers. CIF Dar es Salaam or FOB Mumbai. B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for Tanzania — Bajaj Boxer & Boda Boda",
    intro: "Tanzania's Boda Boda motorcycle taxi sector is one of the fastest-growing in East Africa, driving strong demand for Indian spare parts in Dar es Salaam, Dodoma, Mwanza and Arusha. CrestMAX exports wholesale Bajaj Boxer, TVS HLX and Bajaj RE spare parts from Ludhiana, India to Tanzanian importers — shipped CIF Dar es Salaam or FOB Mumbai.",
    whyPopular: "Tanzania's commercial motorcycle fleet has expanded dramatically in the last decade, with Boda Boda operators providing first-mile and last-mile transport across the country. The demand for OEM-quality parts at wholesale prices from India is strong and growing — particularly for engine overhaul kits, brake parts and suspension components that are consumed regularly in high-use commercial environments.",
    ourSupply: "We supply Bajaj Boxer engine kits, pistons, crankshafts, clutch assemblies, brake pads, suspension parts and electrical components for the Tanzanian market. TVS HLX parts (engine, filters, chains) and Bajaj RE tricycle spares are also available for wholesale buyers.",
    shippingNote: "We ship from Mumbai to Dar es Salaam port. Typical transit time is 20–25 days. We provide full export documentation including SADC certificate of origin where applicable for Tanzanian customs.",
    faqItems: [
      { q: "What Boda Boda parts do you supply for Tanzania?", a: "We supply parts for the most common Boda Boda motorcycles in Tanzania — Bajaj Boxer and TVS HLX. This includes engine kits, pistons, brake systems, clutch plates, chains, sprockets and filters." },
      { q: "Do you provide SADC certificate of origin?", a: "Yes — we can provide SADC Form certificate of origin for Tanzania shipments, which may reduce import duties under SADC trade protocols." },
      { q: "Can you ship CIF to Dar es Salaam?", a: "Yes. We offer FOB Mumbai and CIF Dar es Salaam terms. Contact us with your product list for pricing." },
      { q: "What is the minimum order quantity for Tanzania?", a: "We work with wholesale buyers — typically one 20-foot container load or LCL consolidation. Contact us to discuss MOQ based on your specific product requirements." },
    ],
  },
  {
    name: "Uganda",
    slug: "uganda",
    flag: "🇺🇬",
    port: "Kampala (via Mombasa)",
    region: "East Africa",
    note: "Boda Boda culture drives consistent spare parts demand.",
    popularVehicles: ["Bajaj Boxer", "TVS HLX", "CT100"],
    marketSize: "500,000+ Boda Boda motorcycles — among Africa's densest fleets per capita",
    keyProducts: ["Boda Boda engine kits", "Bajaj Boxer parts", "TVS HLX components", "brake and clutch assemblies"],
    metaTitle: "Spare Parts Supplier for Uganda — Bajaj Boxer & Boda Boda Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj Boxer, TVS and Boda Boda spare parts to Uganda importers. Shipped via Mombasa to Kampala. B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for Uganda — Bajaj Boxer & Boda Boda Parts",
    intro: "Uganda has one of the highest densities of Boda Boda motorcycles in Africa, with hundreds of thousands of commercial motorcycles operating in Kampala, Jinja, Mbarara and across the country. This creates a large, consistent demand for Indian spare parts imported through Mombasa. CrestMAX exports wholesale Bajaj Boxer, TVS HLX and CT100 spare parts from Ludhiana, India to Ugandan importers and distributors.",
    whyPopular: "The Boda Boda is not just transport in Uganda — it is a major employer and economic lifeline. High daily usage means high parts consumption: engine overhaul kits, brake pads, clutch plates and filters are bought in commercial quantities. Ugandan importers route shipments through Mombasa port and road-freight to Kampala, a well-established corridor our buyers regularly use.",
    ourSupply: "We supply Bajaj Boxer (full engine kit, crankshaft, piston, rings, gaskets, clutch, brakes, suspension), TVS HLX (engine components, air filters, oil filters, electrical parts), and CT100 (engine and carburettor parts) for the Ugandan market. All products are OEM-quality from Ludhiana's specialist manufacturers.",
    shippingNote: "Uganda is landlocked — goods enter through Mombasa, Kenya, then road freight to Kampala (~1,200 km). We structure shipments for this corridor, provide all transit documentation, and can coordinate with freight forwarders experienced on the Mombasa–Kampala route. Total transit time India to Kampala: typically 25–32 days.",
    faqItems: [
      { q: "How do goods reach Uganda from India?", a: "Shipments go FOB Mumbai → ocean freight to Mombasa Port, Kenya → road freight to Kampala. This is a well-established import corridor. We can coordinate with experienced freight forwarders for the full door-to-door journey." },
      { q: "What are the most popular spare parts for Boda Boda in Uganda?", a: "Engine overhaul kits, piston sets, brake pads, clutch plates, chain and sprocket sets, and air filters are the highest-volume Boda Boda parts in Uganda — all available from CrestMAX." },
      { q: "Do you have experience shipping to Kampala?", a: "Yes — we supply multiple Ugandan buyers who route through Mombasa. We understand the documentation and logistics requirements for Uganda imports." },
      { q: "Can you supply in mixed containers?", a: "Yes — we can consolidate multiple product types (Boxer parts, TVS parts, CT100 parts) into a single LCL or FCL shipment to maximise your container utilisation." },
    ],
  },
  {
    name: "Ethiopia",
    slug: "ethiopia",
    flag: "🇪🇹",
    port: "Addis Ababa (via Djibouti)",
    region: "East Africa",
    note: "Growing 3-wheeler market. Bajaj RE widely used.",
    popularVehicles: ["Bajaj RE", "Bajaj Boxer", "TVS King"],
    marketSize: "Africa's second most populous country — large and growing vehicle fleet",
    keyProducts: ["Bajaj RE engine parts", "3-wheeler gearbox parts", "TVS King components", "body panels"],
    metaTitle: "Spare Parts Supplier for Ethiopia — Bajaj RE & 3-Wheeler Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj RE, TVS King and 3-wheeler spare parts to Ethiopia importers. Via Djibouti port. B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for Ethiopia — Bajaj RE & 3-Wheeler Parts",
    intro: "Ethiopia is Africa's second most populous country and has a rapidly growing 3-wheeler and motorcycle market, with Bajaj RE auto-rickshaws used widely in Addis Ababa and regional cities. CrestMAX exports wholesale Bajaj RE, TVS King and 2-wheeler spare parts from Ludhiana, India to Ethiopian importers — shipped via Djibouti port.",
    whyPopular: "The Bajaj RE is Ethiopia's dominant 3-wheeler platform, serving as a shared taxi (locally called 'Bajaj') in cities and towns across the country. As Ethiopia's urban population grows and vehicle fleets expand, the demand for affordable, OEM-quality spare parts from India is increasing rapidly. Ethiopian importers are actively seeking reliable direct suppliers to reduce costs and improve parts availability.",
    ourSupply: "CrestMAX supplies Bajaj RE engine components, crankshafts, gearbox parts, body panels and electrical systems; TVS King 3-wheeler parts; and Bajaj Boxer motorcycle parts for the Ethiopian market. We ship via Djibouti, Ethiopia's primary import port, and provide all documentation for Ethiopian customs.",
    shippingNote: "Ethiopia uses Djibouti as its main sea gateway. We ship from Mumbai to Djibouti port, with onward road freight to Addis Ababa (~900 km). Total transit time India to Addis Ababa: typically 28–35 days. We provide all export documents for Ethiopian customs clearance.",
    faqItems: [
      { q: "How do you ship to Ethiopia?", a: "Ethiopia uses Djibouti port as its primary sea gateway. We ship Mumbai → Djibouti → road freight to Addis Ababa. This is a well-established import corridor." },
      { q: "Do you supply Bajaj RE parts for Ethiopia?", a: "Yes — Bajaj RE (auto-rickshaw) parts are a core product. We supply engine kits, gearbox components, body panels, electrical parts and brake assemblies for the RE model." },
      { q: "What is the approximate transit time from India to Addis Ababa?", a: "Typically 28–35 days total: 14–18 days ocean transit to Djibouti, plus port handling and road freight to Addis Ababa." },
      { q: "What currencies and payment terms do you accept?", a: "We accept USD wire transfers (T/T). For established buyers we offer flexible payment terms. Contact us to discuss terms for your order." },
    ],
  },
  {
    name: "DR Congo",
    slug: "dr-congo",
    flag: "🇨🇩",
    port: "Matadi",
    region: "Central Africa",
    note: "Large informal market. High demand for affordable, quality parts.",
    popularVehicles: ["Bajaj Boxer", "TVS HLX", "CT100"],
    marketSize: "Africa's 4th largest country by population — large and underserved spare parts market",
    keyProducts: ["Bajaj Boxer parts", "affordable engine kits", "brake and clutch assemblies"],
    metaTitle: "Spare Parts Supplier for DR Congo — Bajaj Boxer & Motorcycle Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj Boxer and motorcycle spare parts to DR Congo importers. CIF Matadi. B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for DR Congo — Bajaj Boxer & Motorcycle Parts",
    intro: "The Democratic Republic of Congo is one of Africa's largest and most underserved spare parts markets, with a large commercial motorcycle fleet and strong demand for affordable, quality Indian parts. CrestMAX exports wholesale Bajaj Boxer, TVS HLX and CT100 spare parts from Ludhiana, India to DRC importers — shipped to Matadi port.",
    whyPopular: "DR Congo's vast geography and limited road infrastructure make motorcycles essential for transport and commerce. The demand for parts is large and consistent, but importers have historically relied on expensive middlemen. Direct sourcing from Indian exporters like CrestMAX offers DRC importers significant cost savings and more reliable supply.",
    ourSupply: "We supply Bajaj Boxer engine kits, brake assemblies, clutch parts and suspension components; CT100 parts; and TVS HLX components for DRC buyers. Our pricing is competitive for large wholesale orders.",
    shippingNote: "We ship to Matadi port, DRC's main Atlantic port. Transit time from Mumbai is approximately 22–28 days. We provide all export documentation for DRC customs clearance.",
    faqItems: [
      { q: "Do you ship to DR Congo?", a: "Yes — we ship to Matadi port. We have experience with DRC import documentation requirements and can structure shipments for both formal and informal sector buyers." },
      { q: "What motorcycle parts are most in demand in DRC?", a: "Bajaj Boxer engine kits, brake pads, clutch plates, and CT100 engine components are among the most demanded parts for the DRC market." },
      { q: "Can you ship via Mombasa for eastern DRC buyers?", a: "Yes — for buyers in eastern DRC (Goma, Bukavu area), routing via Mombasa and road freight may be faster and more cost-effective. Contact us to discuss routing options." },
      { q: "What is your minimum order?", a: "We work on wholesale quantities. Contact us with your product requirements for MOQ details." },
    ],
  },
  {
    name: "Rwanda",
    slug: "rwanda",
    flag: "🇷🇼",
    port: "Kigali (via Mombasa)",
    region: "East Africa",
    note: "Moto-taxi dominant. Strong parts demand.",
    popularVehicles: ["Bajaj Boxer", "TVS HLX"],
    marketSize: "High moto-taxi density — one of Africa's most regulated motorcycle markets",
    keyProducts: ["Bajaj Boxer parts", "moto-taxi engine kits", "brake and safety components"],
    metaTitle: "Spare Parts Supplier for Rwanda — Bajaj Boxer & Moto-Taxi Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj Boxer and moto-taxi spare parts to Rwanda importers. Via Mombasa to Kigali. B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for Rwanda — Bajaj Boxer & Moto-Taxi Parts",
    intro: "Rwanda has one of Africa's most organised motorcycle taxi (Moto) industries, with thousands of licensed operators in Kigali and other cities. The Bajaj Boxer is the dominant moto-taxi model, creating consistent demand for quality spare parts. CrestMAX exports wholesale Bajaj Boxer and TVS HLX parts from Ludhiana, India to Rwandan importers — shipped via Mombasa to Kigali.",
    whyPopular: "Rwanda's regulated moto-taxi industry requires operators to maintain roadworthy vehicles, which drives demand for quality spare parts. Importers in Kigali source parts directly from India to supply the country's motorcycle garages and operators. The Mombasa–Kigali corridor is a well-established import route.",
    ourSupply: "We supply Bajaj Boxer engine kits, brake systems, clutch assemblies, chain and sprocket sets, and electrical components for Rwandan moto-taxi operators and spare parts traders.",
    shippingNote: "Rwanda is landlocked. Goods route through Mombasa, Kenya (ocean freight) then road freight to Kigali (~1,400 km). Total transit India to Kigali: typically 28–35 days.",
    faqItems: [
      { q: "How do shipments reach Rwanda from India?", a: "Via Mombasa port (Kenya) then road freight to Kigali. This is the standard import corridor for Rwanda — approximately 28–35 days total from India." },
      { q: "Do you supply parts for Bajaj Boxer moto-taxis?", a: "Yes — Bajaj Boxer parts are a core product. We supply engine kits, brake systems, clutch plates, chains, sprockets and electrical components." },
      { q: "Can you provide EAC certificate of origin for Rwanda?", a: "Yes — we can provide East African Community (EAC) certificate of origin, which may reduce import duties for Rwandan buyers." },
      { q: "Do you ship LCL (less than container load) to Rwanda?", a: "Yes — for buyers not yet ready for a full container, we can arrange LCL consolidation through freight forwarders." },
    ],
  },
  {
    name: "Morocco",
    slug: "morocco",
    flag: "🇲🇦",
    port: "Casablanca",
    region: "North Africa",
    note: "North African gateway. Growing motorcycle aftermarket.",
    popularVehicles: ["Bajaj Boxer", "TVS HLX", "CT100"],
    marketSize: "North Africa's most accessible market — gateway to Maghreb region",
    keyProducts: ["Bajaj Boxer engine parts", "CT100 spares", "TVS components"],
    metaTitle: "Spare Parts Supplier for Morocco — Bajaj Boxer & Motorcycle Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj and TVS motorcycle spare parts to Morocco importers. CIF Casablanca. B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for Morocco — Bajaj Boxer & Motorcycle Parts",
    intro: "Morocco is North Africa's most accessible import market and a growing hub for Indian motorcycle spare parts. CrestMAX exports wholesale Bajaj Boxer, CT100 and TVS spare parts from Ludhiana, India to Moroccan importers — shipped CIF Casablanca.",
    whyPopular: "Morocco's growing motorcycle fleet and developing aftermarket create demand for affordable Indian spare parts. Casablanca port offers efficient customs processing and is a regional distribution gateway for the broader Maghreb.",
    ourSupply: "We supply Bajaj Boxer engine and chassis parts, CT100 engine kits, and TVS HLX components for Moroccan wholesale buyers.",
    shippingNote: "We ship from Mumbai to Casablanca. Transit time is approximately 18–22 days. Morocco has a relatively streamlined import process, and we provide all standard documentation for Moroccan customs.",
    faqItems: [
      { q: "Do you ship to Morocco?", a: "Yes — we ship CIF Casablanca. Morocco is one of our accessible North African markets." },
      { q: "What is the transit time from India to Morocco?", a: "Approximately 18–22 days from Mumbai to Casablanca port." },
      { q: "Do you supply Bajaj Boxer parts for Morocco?", a: "Yes — Bajaj Boxer parts including engine kits, brake systems and suspension components are available for Moroccan buyers." },
      { q: "What languages do you communicate in?", a: "We communicate in English. For Moroccan buyers who prefer French correspondence, please let us know and we will try to accommodate." },
    ],
  },
  {
    name: "Angola",
    slug: "angola",
    flag: "🇦🇴",
    port: "Luanda",
    region: "Southern Africa",
    note: "Portuguese-speaking market. 2-wheelers used for deliveries.",
    popularVehicles: ["Bajaj Boxer", "CT100"],
    marketSize: "Growing delivery and commercial motorcycle market in Southern Africa",
    keyProducts: ["Bajaj Boxer parts", "CT100 engine kits", "delivery motorcycle spares"],
    metaTitle: "Spare Parts Supplier for Angola — Bajaj Boxer & Motorcycle Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj Boxer and CT100 motorcycle spare parts to Angola importers. CIF Luanda. B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for Angola — Bajaj Boxer & CT100 Parts",
    intro: "Angola's commercial motorcycle sector is growing rapidly, with 2-wheelers increasingly used for delivery and logistics in Luanda and other cities. CrestMAX exports wholesale Bajaj Boxer and CT100 spare parts from Ludhiana, India to Angolan importers — shipped CIF Luanda.",
    whyPopular: "Angola's urban delivery market is driving 2-wheeler adoption, creating demand for spare parts from reliable Indian suppliers. The Bajaj Boxer is widely used for delivery and courier services.",
    ourSupply: "We supply Bajaj Boxer engine kits, brake assemblies, and CT100 engine and chassis components for Angolan wholesale buyers.",
    shippingNote: "We ship from Mumbai to Luanda port. Transit time is approximately 22–28 days. We provide standard export documentation for Angolan customs (Portuguese-language documentation can be arranged).",
    faqItems: [
      { q: "Do you ship to Angola?", a: "Yes — we ship CIF Luanda. Angola is a growing market for Indian motorcycle spare parts." },
      { q: "Can you provide documentation in Portuguese?", a: "We provide standard export documentation in English. Portuguese translations of commercial invoices can be arranged on request." },
      { q: "What is the transit time from India to Angola?", a: "Approximately 22–28 days from Mumbai to Luanda port." },
      { q: "What are the most popular parts for Angola?", a: "Bajaj Boxer engine kits and brake assemblies are among the most demanded parts for the Angolan market." },
    ],
  },
  {
    name: "South Africa",
    slug: "south-africa",
    flag: "🇿🇦",
    port: "Durban",
    region: "Southern Africa",
    note: "Regional distribution hub potential.",
    popularVehicles: ["Bajaj Boxer", "TVS HLX", "CT100"],
    marketSize: "Africa's most developed economy — regional distribution hub for Southern Africa",
    keyProducts: ["Bajaj Boxer parts", "TVS HLX components", "CT100 spares"],
    metaTitle: "Spare Parts Supplier for South Africa — Bajaj Boxer & Motorcycle Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj Boxer, TVS and CT100 motorcycle spare parts to South Africa importers. CIF Durban. B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for South Africa — Bajaj Boxer & TVS Parts",
    intro: "South Africa is Africa's most developed economy and a key regional distribution hub, with importers in Johannesburg, Durban and Cape Town serving the broader Southern African market. CrestMAX exports wholesale Bajaj Boxer, TVS HLX and CT100 spare parts from Ludhiana, India to South African importers — shipped CIF Durban.",
    whyPopular: "South Africa's well-developed import infrastructure makes it an attractive entry point for Indian spare parts, both for the domestic market and for regional redistribution to Zimbabwe, Zambia, Botswana and Mozambique.",
    ourSupply: "We supply Bajaj Boxer engine kits, suspension and brake parts; TVS HLX components; and CT100 engine and chassis parts for South African and regional distributors.",
    shippingNote: "We ship from Mumbai to Durban — one of Africa's busiest container ports. Transit time is approximately 20–25 days. South Africa has efficient customs procedures and we provide all standard SARS import documentation.",
    faqItems: [
      { q: "Do you ship to South Africa?", a: "Yes — we ship CIF Durban. South Africa is a core market and regional hub for our parts." },
      { q: "Can South African importers redistribute to neighbouring countries?", a: "Yes — many of our South African buyers distribute to Zimbabwe, Zambia, Botswana and Mozambique. We structure shipments and documentation to support regional redistribution." },
      { q: "What is the transit time from India to Durban?", a: "Approximately 20–25 days from Mumbai to Durban." },
      { q: "Do you comply with SARS import requirements?", a: "Yes — we provide all standard export documentation required for SARS clearance including commercial invoice, packing list, certificate of origin and bill of lading." },
    ],
  },
  {
    name: "Algeria",
    slug: "algeria",
    flag: "🇩🇿",
    port: "Algiers",
    region: "North Africa",
    note: "North Africa. Growing import demand.",
    popularVehicles: ["Bajaj Boxer", "CT100"],
    marketSize: "North Africa's largest country by area — growing motorcycle import market",
    keyProducts: ["Bajaj Boxer parts", "CT100 spares", "engine kits"],
    metaTitle: "Spare Parts Supplier for Algeria — Bajaj Boxer & Motorcycle Parts | CrestMAX",
    metaDescription: "CrestMAX exports wholesale Bajaj Boxer and CT100 motorcycle spare parts to Algeria importers. CIF Algiers. B2B wholesale enquiries welcome.",
    h1: "Wholesale Spare Parts Supplier for Algeria — Bajaj Boxer & Motorcycle Parts",
    intro: "Algeria is North Africa's largest country by area and has a growing motorcycle import market. CrestMAX exports wholesale Bajaj Boxer and CT100 spare parts from Ludhiana, India to Algerian importers — shipped CIF Algiers.",
    whyPopular: "Algeria's growing urban motorcycle fleet creates demand for spare parts. Indian exporters offer competitive pricing and quality that appeals to Algerian importers looking to source directly.",
    ourSupply: "We supply Bajaj Boxer engine kits, brake assemblies, and CT100 engine and chassis parts for Algerian wholesale buyers.",
    shippingNote: "We ship from Mumbai to Algiers port. Transit time is approximately 18–22 days.",
    faqItems: [
      { q: "Do you ship to Algeria?", a: "Yes — we ship CIF Algiers. Algeria is a growing market for Indian motorcycle spare parts." },
      { q: "What is the transit time from India to Algeria?", a: "Approximately 18–22 days from Mumbai to Algiers." },
      { q: "Do you supply Bajaj Boxer parts for Algeria?", a: "Yes — Bajaj Boxer engine kits, brake parts and suspension components are available for Algerian buyers." },
      { q: "What documentation do you provide?", a: "Full export documentation: commercial invoice, packing list, certificate of origin, and bill of lading — all required for Algerian customs clearance." },
    ],
  },
];

export function getMarketBySlug(slug: string): Market | undefined {
  return markets.find((m) => m.slug === slug);
}
